[build]
  publish = "/"

[[redirects]]
  from = "/contact"
  to = "/#contact"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[plugins]]
  package = "@netlify/plugin-forms"