[build]
  publish = "/"
  command = ""

[[redirects]]
  from = "/contact"
  to = "/#contact"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[context.production.environment]
  NETLIFY_FORM_RECIPIENT = "aashirulhaque@gmail.com"