[build]
  publish = "/"
  command = ""

[[redirects]]
  from = "/thank-you.html"
  to = "/#contact"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[context.production.environment]
  NETLIFY_FORMS_HANDLER = "true"