[build]
  publish = "/"

[[redirects]]
  from = "/thank-you.html"
  to = "/thank-you.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[plugins]]
  package = "@netlify/plugin-forms"